#pragma once

const char note_name[128][4] = {
    "C3", "C3#", "D3", "D3#", "E3", "F3", "F3#", "G3", "G3#", "A3", "A3#", "B3",
    "C2", "C2#", "D2", "D2#", "E2", "F2", "F2#", "G2", "G2#", "A2", "A2#", "B2",
    "C1", "C1#", "D1", "D1#", "E1", "F1", "F1#", "G1", "G1#", "A1", "A1#", "B1",
    "C",  "C#",  "D",  "D#",  "E",  "F",  "F#",  "G",  "G#",  "A",  "A#",  "B",
    "c",  "c#",  "d",  "d#",  "e",  "f",  "f#",  "g",  "g#",  "a",  "a#",  "b",
    "c1", "c1#", "d1", "d1#", "e1", "f1", "f1#", "g1", "g1#", "a1", "a1#", "b1",
    "c2", "c2#", "d2", "d2#", "e2", "f2", "f2#", "g2", "g2#", "a2", "a2#", "b2",
    "c3", "c3#", "d3", "d3#", "e3", "f3", "f3#", "g3", "g3#", "a3", "a3#", "b3",
    "c4", "c4#", "d4", "d4#", "e4", "f4", "f4#", "g4", "g4#", "a4", "a4#", "b4",
    "c5", "c5#", "d5", "d5#", "e5", "f5", "f5#", "g5", "g5#", "a5", "a5#", "b5",
    "c6", "c6#", "d6", "d6#", "e6", "f6", "f6#", "g6"};

const int basic_note_number[7] = {60, 62, 64, 65, 67, 69, 71};

const char meta_event_type_name[128][40] = {  //
    "sequence number",
    "text event",
    "copyriht notice",
    "sequence or track name",
    "instrument name",
    "lyrics",
    "marker",
    "cue point",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "midi channel prefix",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "set tempo",
    "",
    "",
    "smpte offset",
    "",
    "",
    "",
    "time signature",
    "key signature",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "sequence specific"};

namespace midi
{
const unsigned char off_type = 0x80;
const unsigned char on_type = 0x90;
const unsigned char on_velo = 0x64;
const unsigned char off_velo = 0x00;

static unsigned beat = 960; /* 32*30 */

const unsigned char piano = 0;
const unsigned char guitar = 24;
const unsigned char violin = 40;
};  // namespace midi
